# Generated by Django 5.1.3 on 2024-12-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='image',
        ),
        migrations.AddField(
            model_name='perfume',
            name='image_url',
            field=models.URLField(default='https://ibb.co/YLWps0V'),
        ),
    ]
